### ISSUE TITLE
after login using google, i tried to access a simple api view. gives Unauthorized error

### ISSUE THREAD

**Issue by msd1810** [RealmTeam/django-rest-framework-social-oauth2#148]
my view

`class ldata(APIView):`

 `def get(self, request):`

    `data = "my name"
    return Response(data)`

i can confirm, every time i login using google, it successfully register the user to auth_user & social_auth_usersocialauth table. and auto redirects to profile page.

should i do any additional steps?

but i am getting this error when i access the view's url in browser.

`{
 "detail": "Authentication credentials were not provided."
}`

i have configured everything said here https://github.com/RealmTeam/django-rest-framework-social-oauth2

and added few code to settings for google login

`AUTHENTICATION_BACKENDS = (
'social_core.backends.open_id.OpenIdAuth',
'social_core.backends.google.GoogleOpenId',
'social_core.backends.google.GoogleOAuth2',
'rest_framework_social_oauth2.backends.DjangoOAuth2',
'django.contrib.auth.backends.ModelBackend',
)`

`REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': (
    'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    'rest_framework_social_oauth2.authentication.SocialAuthentication',
),`

`'DEFAULT_PERMISSION_CLASSES': (
    'rest_framework.permissions.IsAuthenticated',
),
}`

`SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "***"`

`SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "***"`

**Comment by marcelchastain** [comment]
@msd1810 
After you login and successfully register the user, you need to get the backend token for that user and include it in each HTTP request's authentication headers.

If you are building an AJAX web app, you'll need to include these authentication headers in each AJAX request to the backend API.

In the docs (under [Social Authentication](https://github.com/RealmTeam/django-rest-framework-social-oauth2#social-authentication))  they talk about testing it using CURL:

```
curl -H "Authorization: Bearer <backend_name> <backend_token>" http://localhost:8000/route/to/your/view
```

Try to access your view's URL using the CURL command above rather than from a browser
