### ISSUE TITLE
Authenticated requests not working

### ISSUE THREAD

**Issue by itsnikhil** [RealmTeam/django-rest-framework-social-oauth2#215]
I have my view which looks like this
```
def hello(request):
   return HttpResponse(str(request.user))
```
`curl -H "Authorization: Bearer <my-token-returned-by-posting-to-/auth/token-with-form-data>" -X GET http://localhost:8000/`

The above command returns "**AnonymousUser**"

I am following the readme and was able to generate tokens but i am not able to "Manage Authenticated Requests"

**Comment by sereneinserenade** [comment]
Hey Nikhil, maybe you're having the problem because you haven't included the 
```<backend-name>```

<img width="457" alt="image" src="https://user-images.githubusercontent.com/45892659/78073306-eb6d6c80-73a0-11ea-97e2-96619004fba5.png">

<img width="918" alt="image" src="https://user-images.githubusercontent.com/45892659/78073423-2e2f4480-73a1-11ea-8827-648192190204.png">

**Comment by ZunaedSifat** [comment]
Hi @itsnikhil , I am having exactly the same problem. Could you solve it somehow?

**Comment by itsnikhil** [comment]
> Hi @itsnikhil , I am having exactly the same problem. Could you solve it somehow?

Hi @ZunaedSifat,
Yes I was able to fix the issue. I don't exactly remember how. I think I made the below mentioned changes. Please try it out once and let me know
```
@api_view(['GET'])
@permission_classes((IsAuthenticated, ))
def hello(request):
   text = {'message': str(request.user)}
   return Response(text)
```
